global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Fetch metrics from microservices every 5 seconds
  evaluation_interval: 5s # Evaluate rules every 5 seconds. Re-evaluate graphs every 5 seconds
scrape_configs:
  - job_name: 'bank-accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bank-accounts:8080' ] # List of instances running. In docker compose the service name is bank-accounts
  - job_name: 'bank-cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bank-cards:9000' ]
  - job_name: 'bank-loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bank-loans:8090' ]
  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8070' ]
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-server:8071' ]